# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
    - R_CHECK_ARGS=" --timings"

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master

deploy:
  provider: script
  script: R -q -e 'devtools::document()'
   on:
  branch: master
