# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global:
    - R_CHECK_ARGS=" --timings"

r_packages:
  - devtools

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy:
  - Rscript -e 'devtools::install(quick = TRUE); install.packages("fpc"); devtools::document(); devtools::build_vignettes(); pkgdown::build_site();'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  local-dir: docs
  on:
    branch: master
#  - Rscript -e 'pkgdown::build_site()'

#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GITHUB_PAT
#  keep-history: true
#  local-dir: docs
#  on:
#    branch: master
