---
title: "Basics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fxtract}
  \usepackage[utf8]{inputenc}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

# calcFeature
```{r, message = FALSE, warning = FALSE}
library(fxtract)
df = data.frame(id = c(rep(1, 10), rep(2, 10)))
df$task = rep(c(rep("task1", 5), rep("task2", 5)), 2)
df$hour = rep(c(rep("hour1", 3), rep("hour2", 2), rep("hour1", 2), rep("hour2", 3)), 2)
df$x = rnorm(20)
df
```

## return 1 value each
```{r}
max_x = function(data) {
  max(data$x)
}
calcFeature(df, group_col = "id", fun = max_x)
```

## return more values at once
```{r}
more_features = function(data) {
  data.frame(max_x = max(data$x), sd_x = sd(data$x))
}
calcFeature(df, group_col = "id", fun = more_features)
```

## group by two columns
```{r}
calcFeature(df, group_col = c("id", "task"), fun = more_features)
```

## group by three colums
```{r}
calcFeature(df, group_col = c("id", "task", "hour"), fun = more_features)
```



