---
title: "Use Cases"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fxtract}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Introduction
make folder studentlife
download data from studentlife [here](http://studentlife.cs.dartmouth.edu/dataset.html)

Goals:
- create features from loggingdata directly from a SQL database, because data is too big for RAM.
- Show a few timestamp helper functions

```{r, eval = FALSE}
library(dplyr)
library(stringr)

db = src_sqlite("SQL_database", create = TRUE)
# loop for all Ids

# Ingestion of Appusage data
lsFiles = list.files(path="studentlife/dataset/app_usage", full.names=TRUE, recursive=FALSE)[1:2]
lsData = lapply(files, function(x) {
    df_temp = read.csv(x, header=TRUE, fileEncoding="UTF-8-BOM") # load file
    userId = str_sub(x,  -7, -5)
    df_temp$userId = userId
    df_temp$source = "app"
    df_temp
})

# Create data frame with app data
calls = do.call(rbind.data.frame, lsData)


# Calls data
lsFiles = list.files(path="studentlife/dataset/call_log", full.names=TRUE, recursive=FALSE)[1:2]
lsData = lapply(files, function(x) {
    df_temp = read.csv(x, header=TRUE, fileEncoding="UTF-8-BOM") # load file
    userId = str_sub(x,  -7, -5)
    df_temp$userId = userId
    df_temp$source = "calls"
    df_temp
})

# Create data frame with calls data
calls = do.call(rbind.data.frame, lsData)

# GPS data
lsFiles = list.files(path="studentlife/dataset/sensing/gps", full.names=TRUE, recursive=FALSE)[1:2]
lsData = lapply(files, function(x) {
    df_temp = read.csv(x, header=TRUE, fileEncoding="UTF-8-BOM") # load file
    userId = str_sub(x,  -7, -5)
    df_temp$userId = userId
    df_temp$source = "gps"
    df_temp
})

# Create data frame with gps data
gps = do.call(rbind.data.frame, lsData)
  
data_all = app %>% bind_rows(calls) %>% bind_rows(gps)

copy_to(db, data_all, name = id)

#test = tbl(db, "u00") %>% select(timestamp)


```

```{r}

```

# Features
## Number different apps
```{r}
featureNumDiffApps = function(data) length(unique(data$RUNNING_TASKS_baseActivity_mPackage))
```

## Mean Number different apps per day
```{r}
phonedata = addDate(phonedata, utc_col = "timestamp")
featureMeanNumDiffAppsPerDay = function(data) {
  n = data %>% dplyr::group_by(date) %>% distinct(RUNNING_TASKS_baseActivity_mPackage) %>% summarize(n = n()) %>% pull(n) 
  return(data.frame(mean = mean(n), sd = sd(n)))
}
```

## gps - maximum distance
```{r}

```

## calls - total number caals

# show shiny app



